language: c
compiler: gcc
script: 
  - gcc --coverage editor.c -o editor
  - make
  - ./editor tester.cpp
  - gcov editor.c
branches:
  only: 
    - add-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
